apiVersion: v1
kind: Pod
metadata:
  name: nginx-banana
  namespace: health-check
  labels:
    app: banana
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "echo I am Banana > /usr/share/nginx/html/index.html"]
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: <AWS_ACCOUNT>.dkr.ecr.<AWS_REGION>.amazonaws.com/nginx_test:latest
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
          - name: regcred
  volumes:
  - name: html-volume
    emptyDir: {}